version: "3.8"
services:
    php:
        #  uruchamia się podczas włączania, plik dockerfile
        build:
            # gdzie
            context: .
            #php varaiable z dockerfile
            target: php
            args:
                - APP_ENV=${APP_ENV}
        environment:
            - APP_ENV=${APP_ENV}
            - CONTAINER_ROLE=app
        #gdzie jakby na serwerze są zapisywane pliki
        working_dir: /var/www
        #gdzie mają się zapisywać nasze dane
        volumes:
            - ./:/var/www
        ports:
            - 8000:8000
        # dopiero po database się odpala
        depends_on:
            - database
    database:
        image: mysql:8.0
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_ROOT_PASSWORD: password
            MYSQL_PASSWORD: ${DB_PASSWORD}
#            MYSQL_ROOT_HOST: localhost
        volumes:
            - db-data:/var/lib/mysql

    node:
        build:
            # gdzie
            context: .
            #php varaiable z dockerfile
            target: node
        volumes:
            - .:/usr/src
            - ./node_modules:/usr/src/node_modules
        tty: true
    vite_docker:
        image: node:alpine
        container_name: vite_docker
        entrypoint: /bin/sh
        ports:
            - 8001:8001
        working_dir: /srv/app
        volumes:
            -   type: bind
                source: ./
                target: /srv/app
        tty: true
volumes:
    db-data: ~
