version: "3.8"
services:
    php:
        #  uruchamia się podczas włączania, plik dockerfile
        build:
            # gdzie
            context: .
            #php varaiable z dockerfile
            target: php
            args:
                - APP_ENV=${APP_ENV}
        environment:
            - APP_ENV=${APP_ENV}
            - CONTAINER_ROLE=app
        #gdzie jakby na serwerze są zapisywane pliki
        working_dir: /var/www
        #gdzie mają się zapisywać nasze dane
        volumes:
            - ./:/var/www
        ports:
            - 8000:8000
        # dopiero po database się odpala
        depends_on:
            - database
    database:
        image: mysql:8.0
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_USER: root
            MYSQL_ROOT_PASSWORD: password
            MYSQL_ROOT_HOST: localhost
        volumes:
            - db-data:/var/lib/mysql
volumes:
    db-data: ~
